FROM postgres:9.5
# 9.5 as ubuntu only has postgresql-client 9.5 so cnanot pg_dump on windows
#RUN su - postgres -c "psql postgres -c \"ALTER SYSTEM SET listen_addresses='*';\""
#RUN su - postgres -c "psql postgres -c \"ALTER SYSTEM SET shared_buffers='1024MB';\""
#RUN su - postgres -c "psql postgres -c \"ALTER SYSTEM SET work_mem='20MB';\""
#RUN su - postgres -c "psql postgres -c \"ALTER SYSTEM SET maintenance_work_mem='128MB';\""
#RUN su - postgres -c "psql postgres -c \"ALTER SYSTEM SET standard_conforming_strings='off';\""

#RUN chmod -R 777 /var/lib/postgresql/data

